# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mutex.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmutex.proto\x12\tmypackage\x1a\x1fgoogle/protobuf/timestamp.proto\":\n\tRequestCS\x12\x12\n\nprocess_id\x18\x01 \x01(\x05\x12\x19\n\x11process_timestamp\x18\x02 \x01(\t\"\x1c\n\nResponseCS\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1a\n\x0cRequestEnter\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\rResponseEnter\x12\x0f\n\x07granted\x18\x01 \x01(\x08\"(\n\x0cRequestWrite\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04line\x18\x02 \x01(\t\" \n\rResponseWrite\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x32\xdf\x01\n\x11RoucairolCarvalho\x12@\n\x0f\x43riticalSection\x12\x14.mypackage.RequestCS\x1a\x15.mypackage.ResponseCS\"\x00\x12\x43\n\x0c\x43\x61niEnterNow\x12\x17.mypackage.RequestEnter\x1a\x18.mypackage.ResponseEnter\"\x00\x12\x43\n\x0cWriteToDiary\x12\x17.mypackage.RequestWrite\x1a\x18.mypackage.ResponseWrite\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mutex_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTCS._serialized_start=59
  _REQUESTCS._serialized_end=117
  _RESPONSECS._serialized_start=119
  _RESPONSECS._serialized_end=147
  _REQUESTENTER._serialized_start=149
  _REQUESTENTER._serialized_end=175
  _RESPONSEENTER._serialized_start=177
  _RESPONSEENTER._serialized_end=209
  _REQUESTWRITE._serialized_start=211
  _REQUESTWRITE._serialized_end=251
  _RESPONSEWRITE._serialized_start=253
  _RESPONSEWRITE._serialized_end=285
  _ROUCAIROLCARVALHO._serialized_start=288
  _ROUCAIROLCARVALHO._serialized_end=511
# @@protoc_insertion_point(module_scope)
