# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mutex_pb2 as mutex__pb2


class RoucairolCarvalhoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriticalSection = channel.unary_unary(
                '/mypackage.RoucairolCarvalho/CriticalSection',
                request_serializer=mutex__pb2.RequestCS.SerializeToString,
                response_deserializer=mutex__pb2.ResponseCS.FromString,
                )
        self.CaniEnterNow = channel.unary_unary(
                '/mypackage.RoucairolCarvalho/CaniEnterNow',
                request_serializer=mutex__pb2.RequestEnter.SerializeToString,
                response_deserializer=mutex__pb2.ResponseEnter.FromString,
                )
        self.WriteToDiary = channel.unary_unary(
                '/mypackage.RoucairolCarvalho/WriteToDiary',
                request_serializer=mutex__pb2.RequestWrite.SerializeToString,
                response_deserializer=mutex__pb2.ResponseWrite.FromString,
                )


class RoucairolCarvalhoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriticalSection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaniEnterNow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteToDiary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoucairolCarvalhoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriticalSection': grpc.unary_unary_rpc_method_handler(
                    servicer.CriticalSection,
                    request_deserializer=mutex__pb2.RequestCS.FromString,
                    response_serializer=mutex__pb2.ResponseCS.SerializeToString,
            ),
            'CaniEnterNow': grpc.unary_unary_rpc_method_handler(
                    servicer.CaniEnterNow,
                    request_deserializer=mutex__pb2.RequestEnter.FromString,
                    response_serializer=mutex__pb2.ResponseEnter.SerializeToString,
            ),
            'WriteToDiary': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteToDiary,
                    request_deserializer=mutex__pb2.RequestWrite.FromString,
                    response_serializer=mutex__pb2.ResponseWrite.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mypackage.RoucairolCarvalho', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoucairolCarvalho(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriticalSection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.RoucairolCarvalho/CriticalSection',
            mutex__pb2.RequestCS.SerializeToString,
            mutex__pb2.ResponseCS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CaniEnterNow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.RoucairolCarvalho/CaniEnterNow',
            mutex__pb2.RequestEnter.SerializeToString,
            mutex__pb2.ResponseEnter.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteToDiary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mypackage.RoucairolCarvalho/WriteToDiary',
            mutex__pb2.RequestWrite.SerializeToString,
            mutex__pb2.ResponseWrite.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
